version: '3'
services:
  backend-application:
    container_name: shield-back-end
    image: shield-spring-app
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
      - kafka1
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092"
  frontend:
    container_name: shield-front-end
    image: shield-react-app
    ports:
      - "3001:3000"
    depends_on:
      - backend-application
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: productstore
    volumes:
      - pg-data:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "abc_topic:1:1,ResultTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
  promtail:
    image: grafana/promtail:2.4.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /home/bhanu/data-shield/promtail-config.yml:/etc/promtail/config.yml
    ports:
      - "9080:9080"
    depends_on:
      - backend-application
      - frontend
      - postgresql
      - kafka1
      - zookeeper
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
volumes:
  pg-data:







